[package]
name = "hello_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
component = "0.1.1"
rust-analyzer = "0.0.1"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
serde_json = "1.0"
